env:
  browser: true
  es2021: true
extends:
  - plugin:prettier/recommended
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
rules:
  prettier/prettier: ["error", { "singleQuote": true }]
  no-console: 0
  arrow-body-style: 0
  react/function-component-definition: 0
  react/jsx-filename-extension: 0
